paths:
  gcsfs_path: gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3
  zarr_path:  /media/user/h/minchan/GC_ERA5
  zarr_name:  _test.zarr
  repo_path:  /home/minchan/arco-era5-downloader
  output_path:  /home/minchan/arco-era5-downloader/logs

dask:
  dask_delay: True

# For debugging
start_date: 2024-02-27 00:00:00
end_date: 2024-03-15 00:00:00 
timestep_hour: 6

shift_forcing: 0
variables: ['2m_temperature','temperature']
forcing_variables: ['sea_ice_cover', 'sea_surface_temperature']