paths:
  zarr_name:  GC_ERA5.zarr

timestep_hour: 6
shift_forcing: 0

variables: [
    '2m_temperature',
    'mean_sea_level_pressure',
    '10m_v_component_of_wind',
    '10m_u_component_of_wind',
    'temperature',
    'geopotential',
    'u_component_of_wind',
    'v_component_of_wind',
    'vertical_velocity',
    'specific_humidity',
    'total_precipitation',
    'geopotential_at_surface',
]
forcing_variables: ['toa_incident_solar_radiation','land_sea_mask']
